### PR TITLE
  postgres extension

### PR DESCRIPTION
**Pull request by tpo**
Hello Nico,

here's a trivial type to add. It also contains some stuff coming from your own git tree, please ignore that, I think it should merge just fine.

Viele Grüsse,
*t

### CODE REVIEW

**Comment by telmich** [comment]
Wow! This is really cool! I somehow did not receive notifications from github for this one, sorry for the huge delay!

**Comment by tpo** [comment]
:)

**Comment by darko-poljak** [comment]
@tpo Hi! Can you rename man.text to man.rst and change format to reStructuredText? cdist docs are in this format now. And then we can review this PR again.

**Comment by tpo** [comment]
@darko-poljak as requested, I've moved to man.rst, as you should be able to see in commit 60906c0. Nothing else has been touched in that commit.

**Comment by darko-poljak** [comment]
@tpo Can you please move to GPLv3+ in man.rst?
And also remove cdist-type reference in SEE ALSO.
New docs are built using sphinx and whole docs are not a set of man pages anymore.
So cdist-type man page does not exist anymore, it is a chapter in new web docs.

**Comment by tpo** [comment]
@darko-poljak done: 267d823

**Pull request merged**
