### PR TITLE
Please merge __package_dpkg type

### PR DESCRIPTION
**Pull request by tpo**
Dear Nico,

as allready discussed via PM, please add the __package_dpkg type which lets you install local Debian packages from files/\* on the target.

Comments wellcome, thanks,
*t

### CODE REVIEW

**Comment by darko-poljak** [comment]
@telmich Can you review this one?
@tpo Can you migrate man.text to reStructuredText man.rst ?

**Comment by tpo** [comment]
@darko-poljak as requested, I've moved to man.rst, as you should be able to see in commit 8e3281a. Nothing else has been touched in that commit.

**Comment by tpo** [comment]
@darko-poljak : With commit 6bcfdec I've also removed the reference to cdist_type and moved to GPL3+ as you've requested here: https://github.com/ungleich/cdist/pull/360#issuecomment-264110087

**Comment by darko-poljak** [comment]
@tpo Just one more '=' in man.rst header. Sorry for torturing you.

**Comment by darko-poljak** [comment]
@tpo How about changing this type so that you don't have to specify both full path and deb file basename?
For example, __object_id is path to deb file
__package_dpkg $__type/files/bar_1.4.deb
and then you can use `basename` to get file's name.
And what do you think about allowing future type extensions by adding an `action` parameter which if not specified defaults to install? As is now, this type supports only install action.

**Comment by tpo** [comment]
Hi @darko-poljak 

I wrote __package_dpkg and __postgres_extension while working on a project that was using cdist. Since I am not using cdist these times I will not invest a lot of time into this. Patching the documentation was easy so I did that for you, but changing the interface requires more work.

Changing the interface as you propose should be upwards compatible and can be done later if anybody is willing to do the effort.

**Comment by tpo** [comment]
I've added the '=' to the title as you've requested in commit 4370efd

**Comment by darko-poljak** [comment]
@tpo Aha, I see, ok. Thanks for this additional work.
@telmich Fine with you to merge this PR?

**Pull request merged**
