### PR TITLE
add __acl: Basic wrapper around setfacl

### PR DESCRIPTION
**Pull request by 4nd3r**
@telmich asked:
> Why do you think recursive should be the default?

to keep things simple and because mostly, when dealing with ACL entries, you want recursive operation.

code will get very complex and error prone, if we want to differentiate between recursive and non-recursive ACL entries because `getfacl` doesn't tell (without `-R` and even with it, parsing it sanely is rather difficult, YMMV) if ACL entry is also on subdirs and files. so as first iteration I tried to get type which would cover 90% of my use cases. will see about rest of 10% in the future :-).

also about `--remove` flag - maybe some other phrase would be better, but the idea is that all destructive operations should be explicit.

### CODE REVIEW

**Comment by 4nd3r** [comment]
also, i found some bugs. please do not merge yet.

**Comment by 4nd3r** [comment]
ok, i think it's now somewhat better. please review and comment.

**Comment by 4nd3r** [comment]
wow, getting some fresh air helps.

so, i should add `--recursive` and `--default`. this way i can resolve another 5% of my use cases.

for example set non-default group to parent directroy, but treat known subdirectories differently.

will test that tomorrow.

**Comment by darko-poljak** [comment]
@4nd3r I suggest to add safety check for supported OSes. For example, FreeBSD setfacl does not support -R option.

**Comment by 4nd3r** [comment]
> I suggest to add safety check for supported OSes.

and solaris doesn't support `-x`. should check should be whitelist or blacklist?

i think it's easier just take all linux dists from __explorer/os and write them down.

**Comment by 4nd3r** [comment]
i think it's good now. any more comments?

**Comment by darko-poljak** [comment]
@4nd3r Also check OS in explorer for getfacl. E.g. FreeBSD getfacl has neither -c nor -p option.

**Comment by 4nd3r** [comment]
-c and -p are not needed actually, because grep :>

**Comment by darko-poljak** [comment]
@4nd3r One more thing. If commit history isn't necessary, please rebase :)

@telmich Any remarks on this new type?

**Comment by 4nd3r** [comment]
rebased

**Pull request merged**
