### PR TITLE
Feature output streams

### PR DESCRIPTION
**Pull request by darko-poljak**
This PR is 99% based on @asteven 's initial implementation.
Creating it for further discussion and testing.

### CODE REVIEW

**Comment by asteven** [comment]
It seems we don't yet handle errors in intial manifest nicely.

e.g. with output_streams
```
[15:18:52] crius:~% cdist-hpc config -v eu-sb-c-02.hpc.ethz.ch
INFO: eu-sb-c-02.hpc.ethz.ch: Starting configuration run
/tmp/tmpsuli67v4/cd102a66c34723b7af08c82d9fbaee83/data/conf/manifest/hpc/euler: line 11: ETHZ_CLUSTER_NAME: unbound variable
ERROR: eu-sb-c-02.hpc.ethz.ch: Command failed: /tmp/tmpsuli67v4/cd102a66c34723b7af08c82d9fbaee83/data/conf/manifest/init with returncode: 1
stdout: None
ERROR: cdist: Failed to configure the following hosts: eu-sb-c-02.hpc.ethz.ch
```

without output_streams
```
[15:18:52] crius:~% cdist-hpc config -v eu-sb-c-02.hpc.ethz.ch
INFO: eu-sb-c-02.hpc.ethz.ch: Starting configuration run
/tmp/tmpsuli67v4/cd102a66c34723b7af08c82d9fbaee83/data/conf/manifest/hpc/euler: line 11: ETHZ_CLUSTER_NAME: unbound variable
ERROR: eu-sb-c-02.hpc.ethz.ch: Command failed: /tmp/tmpsuli67v4/cd102a66c34723b7af08c82d9fbaee83/data/conf/manifest/init with returncode: 1
stdout: None
ERROR: cdist: Failed to configure the following hosts: eu-sb-c-02.hpc.ethz.ch
[15:19:03] crius:~% 
```

**Comment by asteven** [comment]
It seems that for code-remote execution on the target the env variables are not longer injected.

iow: __object and friends are not defined when code-remote is executed

```
[15:21:28] crius:~% cdist-hpc config -v eu-sb-c-02.hpc.ethz.ch
INFO: eu-sb-c-02.hpc.ethz.ch: Starting configuration run
INFO: eu-sb-c-02.hpc.ethz.ch: Processing __apt_update_index/
INFO: eu-sb-c-02.hpc.ethz.ch: Processing __file/etc/cdist-config-versions
INFO: eu-sb-c-02.hpc.ethz.ch: Processing __key_value/__sysctl/net.nf_conntrack_max
ERROR: eu-sb-c-02.hpc.ethz.ch: Command failed: ssh -o User=root -o ControlPath=/tmp/tmp3l3htnpt/s -o ControlMaster=auto -o ControlPersist=2h eu-sb-c-02.hpc.ethz.ch /bin/sh -e /var/lib/cdist/object/__key_value/__sysctl/net.nf_conntrack_max/.cdist-jfd5_4t0/code-remote with returncode: 1
stdout: None
---- object --------------------------------------------------------------
name: __key_value/__sysctl/net.nf_conntrack_max
path: /tmp/tmpa0bp0_r7/cd102a66c34723b7af08c82d9fbaee83/data/object/__key_value/__sysctl/net.nf_conntrack_max/.cdist-jfd5_4t0
source: ['/tmp/tmpa0bp0_r7/cd102a66c34723b7af08c82d9fbaee83/data/conf/type/__sysctl/manifest']
type: /tmp/tmpa0bp0_r7/cd102a66c34723b7af08c82d9fbaee83/data/conf/type/__key_value
code-remote:stderr -------------------------------------------------------
cat: /parameter/state: No such file or directory
cat: /parameter/file: No such file or directory

ERROR: cdist: Failed to configure the following hosts: eu-sb-c-02.hpc.ethz.ch
[15:24:00] crius:~% 
```

**Comment by darko-poljak** [comment]
@asteven Yes, in code.py in _run_code it is missed to pass env to x.run_script.

**Comment by darko-poljak** [comment]
@asteven I committed a fix, you can try again.
I will take care of initial manifest error handling later.

**Comment by darko-poljak** [comment]
@asteven Also committed init manifest error handling.
Sample run:
<pre>
$ ./bin/cdist config -i ~/.cdist/manifest/init-with-error 192.168.56.30
ERROR: 192.168.56.30: Command failed: /bin/sh -e /home/darko/.cdist/manifest/init-with-error with returncode: 2
stdout: None
---- initial manifest ----------------------------------------------------
initial manifest: /home/darko/.cdist/manifest/init-with-error
init:stderr --------------------------------------------------------------
usage: __file [--state STATE] [--group GROUP] [--mode MODE] [--owner OWNER]
              [--source SOURCE]
              object_id
__file: error: unrecognized arguments: source -

ERROR: cdist: Failed to configure the following hosts: 192.168.56.30
</pre>

**Comment by darko-poljak** [comment]
Closing this PR.
We are continuing this feature in branch
https://github.com/ungleich/cdist/tree/feature/output_streams

**Pull request closed without merging**
