### PR TITLE
Add openvz/lxc discovery

### PR DESCRIPTION
**Pull request by sleemburg**
Hi Nico,

This is a pull request for a simple change to recognize openvz/lxc containers.
Also there is the addition of scientific for Scientific Linux.

Kind regards,
Stephan

### CODE REVIEW

**Comment by telmich** [comment]
@darko-poljak I'd like to merge this PR, but I've seen a change to the web site  - can you check/ensure that/if os.mdwn has been moved to sphinx already or not?

Just don't want this PR to create inconsistencies

**Comment by darko-poljak** [comment]
@telmich os.mdwn is not moved to sphinx, it is part of static web. So you can merge this PR.

**Comment by sleemburg** [comment]
Hi,

I have done quite some scripting in / for / with cdist. I have still a
couple of other patches  that I want to submit.

Today, I cloned the unstable branch and it broke, as I use some
'scripting library' that outputs info to stderr.
But the stderr output got into the remote-code with the stdout output.
So that broke the remote scripting.

Therefore, I want to submit the patches for both the 4 and latest 3
branch. But I cannot really test the 4 branch modifications.

Is that a problem for you?

I know that they work in the 3 branch.

Anyway, thanks for cdist.

Kind regards,
Stephan

**Comment by darko-poljak** [comment]
Stephan,
thanks for this, I know where is the problem in master regarding gencode
and stderr.
I will fix it and then you can try it again.

**All work and no play makes Jack a dull boy**

**Comment by sleemburg** [comment]
Ah, ok.. thanks. I will try again after your commits.

Again, thanks for all you efforts and for cdist.

**Comment by darko-poljak** [comment]
@sleemburg You can try your change with cdist master branch.
You will make a separate PR for this new changes, right?

@telmich Regarding docs and os.mdwn, you can merge this PR.

**Comment by telmich** [comment]
@sleemburg can you update docs/changelog, please? afterwards it's ready to merge

**Comment by telmich** [comment]
@sleemburg ping

**Comment by sleemburg** [comment]
Sorry for the late reply, I have been very busy.

I updated doc/changelog. I put the comment at the next: tag. Is that ok?

**Comment by telmich** [comment]
Thanks for the update - let's go with it!

**Pull request merged**
