### PR TITLE
RFC: rewrite __line type for --before and --after support

### PR DESCRIPTION
**Pull request by asteven**

### CODE REVIEW

**Comment by asteven** [comment]
I am using this as my __line type from now on to test it.

**Comment by telmich** [comment]
A lot of changes - hard to verify in github, but I have good trust in you two -> gtg!

**Comment by asteven** [comment]
Do not merge yet. There is some regression. The ./explorer/state does not work properly in all cases.
So far I've seen that entries in /etc/ssh/ssh_known_hosts are not properly detected as 'present'.
Looking into it.

**Comment by asteven** [comment]
Works for me know. Let me use this for a while in production before merging.

**Comment by asteven** [comment]
@darko-poljak did you notice how I just read the parameters straight from awk in the generated code?
No more escaping strings and shit like that. Coding like this could simplify many types we have.

**Comment by darko-poljak** [comment]
@asteven Yes. Even the whole type's script could be awk script, where appropriate.

**Comment by darko-poljak** [comment]
@asteven Hi! Is new line working fine?

**Comment by asteven** [comment]
Have not seen any problems yet.

**Pull request merged**
