### PR TITLE
add CDIST_BETA env variable

### PR DESCRIPTION
**Pull request by 4nd3r**

### CODE REVIEW

**Comment by telmich** [comment]
Cool idea!

**Comment by telmich** [comment]
I just wanted to merge it, but saw that there is no documentation for it -- can you add it? And then we are good for merge!

**Comment by darko-poljak** [comment]
@telmich Just started to type the same :)
@4nd3r please document it in docs/src/cdist-reference.rst.sh and docs/src/man1/cdist.rst in ENVIRONMENT section and in -b option description.

**Comment by 4nd3r** [comment]
yeah, just looking at ` docs/src/man1/cdist.rst` and `-b, --beta` mentioned in multiple places...

just copy-paste?

**Comment by darko-poljak** [comment]
@4nd3r Well, yes, copy-paste.

And I forgot to mention, add the same sentence in parser help for -b/--beta option so cdist.rst man page reflects cdist -h. This is in cdist/argparse.py. After that this PR will be ready for merging.

**Comment by darko-poljak** [comment]
@4nd3r There is one more place where this env var could be mentioned. In cdist/__init__.py in CdistBetaRequired hint message.

**Comment by darko-poljak** [comment]
And I am for removing this `elif` in check_beta and set `default='CDIST_BETA' in os.environ` for -b/--beta option.

**Comment by 4nd3r** [comment]
@darko-poljak sorry, i'm not very good with python. what do you mean?

**Comment by telmich** [comment]
@4nd3r let us know if we torture you too much!

**Comment by 4nd3r** [comment]
torture is fine, i just don't have much experience with python :>

**Comment by darko-poljak** [comment]
@4nd3r Sorry. I mean, leave `check_beta` as is, don't add lines:
<pre>
    elif 'CDIST_BETA' in os.environ:
        args_dict['beta'] = True
</pre>

but change:
<pre>
    parser['beta'].add_argument(
           '-b', '--beta',
           help=('Enable beta functionalities. '
                 'Can also be enabled using CDIST_BETA env var.'),
           action='store_true', dest='beta', default=False)
</pre>
to:
<pre>
    parser['beta'].add_argument(
           '-b', '--beta',
           help=('Enable beta functionalities. '
                 'Can also be enabled using CDIST_BETA env var.'),
           action='store_true', dest='beta', default='CDIST_BETA' in os.environ)
</pre>.

This way, if option is specified it will be used. If option is not specified default value will be used and this default value is determined by presence of CDIST_BETA in env.
If CDIST_BETA is set beta is set to True, otherwise it is set to False.

**Comment by 4nd3r** [comment]
...and I thought I can get it merged with less than 30 minutes.

anyway, if that's all then please merge. thanks.

**Comment by darko-poljak** [comment]
Well, you miss

**Comment by darko-poljak** [comment]
Arrrghhh! Sorry for that, touchscreen on my smartphone.

**Pull request merged**
