### PR TITLE
__jail_freebsd10

### PR DESCRIPTION
**Pull request by jdguffey**
Added support for FreeBSD 10.x jails

Moved __jail to __jail_freebsd9, created __jail_freebsd10, created stub __jail to select the appropriate jail subtype to properly manage jails on FreeBSD systems based on remote OS version.

### CODE REVIEW

**Comment by darko-poljak** [comment]
@jdguffey Could you please update docs/changelog?

**Comment by jdguffey** [comment]
Sure. I don't know when the new version will be released or what release engineering looks like on this project at this time, but feel free to correct what I add.

**Comment by jdguffey** [comment]
Done.

**Comment by darko-poljak** [comment]
@jdguffey  Just replace 
`4.1.1: 2016-06-06`
with
`next:`

**Pull request merged**
