### PR TITLE
__systemd_unit improvements

### PR DESCRIPTION
**Pull request by lubo**

### CODE REVIEW

**Comment by darko-poljak** [comment]
Hi!

I see a fresh commit today.
Is it ready for merging or you have something else in the queue?

**Comment by lubo** [comment]
Hey, it's ready. Go for merge if you're OK with the changes.

**Comment by lubo** [comment]
Btw, merging these changes and releasing a new cdist version would be an awesome Christmas present from @ungleich :smile:

**Comment by lubo** [comment]
It's unfortunate you've chosen to squash these commits, it's difficult to tell which code is related which change now. Is there any policy I shall follow? E.g., to send multiple PRs if I don't want to have my commits squashed?

**Comment by darko-poljak** [comment]
No, no multiple PRs. I used squash when PR history was a mess and this form
of PR merge stayed as default. I will try to think more when merging,
whether it should be squashed or not.

Is current state so disturbing?

** All work and no play makes Jack a dull boy **

Darko


On Dec 29, 2017 18:17, "Ľubomír Kučera" <notifications@github.com> wrote:

It's unfortunate you've chosen to squash these commits, it's difficult to
tell which code is related which change now. Is there any policy I shall
follow? E.g., to send multiple PRs if I don't want to have my commits
squashed?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/ungleich/cdist/pull/606#issuecomment-354473830>, or mute
the thread

**Comment by lubo** [comment]
No. These changes were simple, so it's not that bad. Thanks.

**Comment by darko-poljak** [comment]
Good. And sorry for the inconvenience.

** All work and no play makes Jack a dull boy **

Darko

**Pull request merged**
