### PR TITLE
Bugfix for: __ssh_authorized_keys overwrites existing keys #577

### PR DESCRIPTION
**Pull request by darko-poljak**

### CODE REVIEW

**Comment by darko-poljak** [comment]
@pcoder Can you checkout my branch and test this fix, please?

**Comment by asteven** [comment]
+1 if it works, don't have time to test

**Comment by darko-poljak** [comment]
@pcoder Please verify if it works.

**Comment by pcoder** [comment]
@darko-poljak Sorry for the late reply.
I only tested out with limited test cases. And with all of those, the fix works very good. 👍

**Comment by pcoder** [comment]
Just wondering if it would be a good idea to `trim`/`strip` the keys before adding them?

**Comment by darko-poljak** [comment]
@pcoder Hm... yes. And even validate that key is valid. I will add these too.

**Comment by darko-poljak** [comment]
@pcoder It seems that shell code already trims such key. I also added key validation. In case of invalid key error message is printed and type exits with return value 1. Please test.

**Comment by pcoder** [comment]
Hi @darko-poljak, 

__ssh_authorized_keys can be used to configure multiple keys at the same time.
In this regard, I wonder if it would be possible to avoid invalid keys only and configure the other keys that are valid.

Currrently, if I have n keys to configure and if one of them is an invalid one, then none of the keys get configured.

**Comment by asteven** [comment]
Pcoder wrote on 09/16/2017 10:18 AM:
> Hi @darko-poljak,
> 
> __ssh_authorized_keys can be used to configure multiple keys at the same time.
> In this regard, I wonder if it would be possible to avoid invalid keys only and configure the other keys that are valid.
> 
> Currrently, if I have n keys to configure and if one of them is an invalid one, then none of the keys get configured.
> 

Don't use invalid ssh keys? Maybe?

**Comment by darko-poljak** [comment]
I am not sure if even adding parameter - - ignore-invalid is good idea,
user would not know which keys are and which are not configured. Can you
validate keys before calling cdist?

** All work and no play makes Jack a dull boy **

Darko

**Comment by e-s-a-i** [comment]
Checking for a valid key should also follow the correct format, as the file may contain parameters. 
http://man.openbsd.org/OpenBSD-current/man8/sshd.8#AUTHORIZED_KEYS_FILE_FORMAT

**Comment by pcoder** [comment]
Sure, the keys can be validated beforehand

**Comment by darko-poljak** [comment]
@e-s-a-i There are type parametera for options and comment. Key parameter should hold only key type and the key. But we can check if anything after the key, whitespace separated, is present.

**Comment by asteven** [comment]
I've been using this type for +5 years without any problem ever.
If we can easily ignore invalid keys that are already on the target, than let's do that.
But I don't want to jump through hoops and make the code more complicated or fragile for a one time use case that can be solved otherwise. I don't want to start validating input parameters against validity. This will add a maintenance burden for the future. e.g. SSH supports a new type/format/whatever of key -> we have to jump and adapt.
Keep it simple.

**Comment by darko-poljak** [comment]
@asteven I agree, let's keep it simple. The already implemented validation
in this PR makes sense because, for example, entry explorer already works
for valid keys, but not for invalid. So let's check it with the same tr+awk
code. Otherwise, you can add an invalid key but never remove the same. So,
let's stay with this PR's code but don't complicate it further. Agree?

** All work and no play makes Jack a dull boy **

Darko

On Sep 16, 2017 6:57 PM, "Steven Armstrong" <notifications@github.com>
wrote:

I've been using this type for +5 years without any problem ever.
If we can easily ignore invalid keys that are already on the target, than
let's do that.
But I don't want to jump through hoops and make the code more complicated
or fragile for a one time use case that can be solved otherwise. I don't
want to start validating input parameters against validity. This will add a
maintenance burden for the future. e.g. SSH supports a new
type/format/whatever of key -> we have to jump and adapt.
Keep it simple.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ungleich/cdist/pull/579#issuecomment-329980868>, or mute
the thread

**Pull request merged**
