### PR TITLE
Pep8

### PR DESCRIPTION
**Pull request by darko-poljak**
Hello!

I ran pep8 for cdist and fixed code style according to pep8.

### CODE REVIEW

**Comment by telmich** [comment]
Omg! Alright, let's get things cleaned up. @asteven you might want to merge again after this merge, so code doesn't diverge too much

**Comment by asteven** [comment]
Guess I will not merge anymore at all. Way to quickly moving target for all my patch sets.

**Comment by telmich** [comment]
@asteven I suggest to move your patch set upstream -- let's talk about it in person next week

**Comment by telmich** [comment]
@asteven I suggest to move your patch sets upstream -- let's talk about it in person next week

**Pull request merged**
