### PR TITLE
Add pre-exists state to __file

### PR DESCRIPTION
**Pull request by matthijskooijman**
Here's two (unrelated) changes I needed and which seem reusable. Commit messages should be self-explaining. If you prefer separate pull requests, let me know.

### CODE REVIEW

**Comment by darko-poljak** [comment]
@matthijskooijman  Can you separate this PR into two? Thanks!

**Comment by matthijskooijman** [comment]
Done!

**Comment by telmich** [comment]
Interesting and no objections to the PR, but curious: when do you use pre-exists?

**Comment by darko-poljak** [comment]
@matthijskooijman You could also describe pre-exists use case in man.rst :)

**Comment by matthijskooijman** [comment]
My usecase is that I modify the bootup sequence of a beagleboard to start a specific script on startup, but that script should already be present on the default install of the beagleboard. To prevent referencing a script that does not exist and silently failing to boot, I want to check its existence, but if it does not exist, I don't know what the script should contain (and an empty file won't do either), so I can't use the normal exists.

I couldn't think of a nice example for the manpage that uses standard files, but I couldn't really think of anything that was generic enough. Suggestions are welcome :-)

**Comment by darko-poljak** [comment]
So this is a way to check that file already exists at remote.

**Comment by matthijskooijman** [comment]
Yup

**Comment by telmich** [comment]
good to go

**Pull request merged**
