### PR TITLE
Add archiving support

### PR DESCRIPTION
**Pull request by darko-poljak**
Hello!

I added archiving support to cdist. New option:
<pre>
  -R [{tar,tgz,tbz2,txz}], --use-archiving [{tar,tgz,tbz2,txz}]
                        Operate by using archiving with compression where
                        apropriate. Supported values are: tar - tar archive,
                        tgz - gzip tar archive (the default), tbz2 - bzip2 tar
                        archive and txz - lzma tar archive.
</pre>

Currently, it is used only in `cdist/exec/remote.py` in `transfer` function.
If source is directory and contains more than 1 file then archiving will be used (if -R option is specified).
That means that directory content will be tared (with compression, depending on option), tar file is transferred to the remote side, extracted at remote and deleted at remote and local.
For local side archiving `tarfile` python module is used.
For remote side extracting remote exec of `tar -x ...` is used, with options depending on -R optional argument.

I ran simple manifest against a test machine three times for each archiving option. Here are timings:
**Without archiving**
15,09
13,92
15,23

**TAR**
10,60
9,46
9,40

**TGZ**
10,03
9,40
9,03

**TBZ2**
9,16
9,23
9,23

**TXZ**
9,24
9,25
9,81

-R option is currently added to beta options.

@telmich @asteven What do you think?

### CODE REVIEW

**Comment by telmich** [comment]
Interesting! While you are at it, can you compare those three options with and without ssh compression enabled? (it is not clear from above, if it is or not)

**Comment by darko-poljak** [comment]
@telmich By current design, for each file in directory cdist does one scp sub-process. imho, using compression option would not speed up anything significantly, since explorer and parameter files are small. So you have  17 global explorers and 17 scp sub-processes. From ssh man page: From ssh man page, for -C option:

Compression is
             desirable on modem lines and other slow connections, but will
             only slow down things on fast networks. 

The main idea with archiving is to create one file that is transferred with scp to remote with one additional ssh sub-process for tar -x. Compression ia just a side effect of tar supporting it. 

But I can try current cdist impl with -C.

**Comment by telmich** [comment]
@darko-poljak Sorry for the confusion - what I mean is: you are using **compression** with xz/bzip2/gzip already here. While this **might** make sense, I was wondering how the tar compression is unfluenced positively or negatively, if we run ssh with compression as well.

Hope that makes it more clear now :-)

**Comment by darko-poljak** [comment]
@telmich I understand now. I will test it.

**Comment by darko-poljak** [comment]
@telmich  Interesting, without archiving:
<pre>
$ ./bin/cdist config -b -v -i ~/.cdist/manifest/init --remote-copy 'scp -C -o User=root' -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test )
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 27.18 seconds
$ ./bin/cdist config -b -v -i ~/.cdist/manifest/init --remote-copy 'scp -C -o User=root' -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test )
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 27.36 seconds
$ ./bin/cdist config -b -v -i ~/.cdist/manifest/init  -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test ) 
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 12.89 seconds
$ ./bin/cdist config -b -v -i ~/.cdist/manifest/init  -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test )
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 13.53 seconds
</pre>

with default archiving (tar + gzip):

<pre>
$ ./bin/cdist config -b -R -v -i ~/.cdist/manifest/init --remote-copy 'scp -C -o User=root' -- $(head -1 ~/ungleich/data/openne
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 11.99 seconds
$ ./bin/cdist config -b -R -v -i ~/.cdist/manifest/init --remote-copy 'scp -C -o User=root' -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test )
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 11.76 seconds
$ ./bin/cdist config -b -R -v -i ~/.cdist/manifest/init -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test ) 
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 9.00 seconds
$ ./bin/cdist config -b -R -v -i ~/.cdist/manifest/init -- $(head -1 ~/ungleich/data/opennebula-cdist-master-test )
INFO: 185.203.114.185: Starting configuration run
[xxx] host.file
[xxx] host.file2
[xxx] host.file3
INFO: 185.203.114.185: Finished successful run in 8.96 seconds
</pre>

scp -C in any case is slower then not using it. I think this is because explorer and parameter files are small, network/internet connection is fast enough and -C

<pre>
             Requests compression of all data (including stdin, stdout,
             stderr, and data for forwarded X11, TCP and UNIX-domain
             connections).
</pre>

man page also mentions this:

<pre>
             Compression is
             desirable on modem lines and other slow connections, but will
             only slow down things on fast networks.
</pre>

**Pull request merged**
