### PR TITLE
Handle missing files with __line (dry-run)

### PR DESCRIPTION
**Pull request by thriqon**
Second commit is optional.

### CODE REVIEW

**Comment by asteven** [comment]
Thanks for the patch.
But to me it looks like you are using it wrongly.

If the file does not exist we should fail. Question here is if we can fail in a more user friendly way then just letting awk die hard.

We can't just create the file if it is not there. We have no clue how user/group/permissions should be.

The proper way to use this is by using the __file type to ensure the file exists.

e.g.
```
__file /tmp/my-file \
   --state present
require="__file/tmp/my-file" \
   __line my-line \
      --file /tmp/my-file \
      --line 'hello world'
```

Like this the explorer works fine, because it is run after the __file type has done it's job.
Also no need to create the file in gencode-remote.

**Comment by asteven** [comment]
Sorry, just saw that I missed the context from #675.

**Comment by thriqon** [comment]
Yes, it usually works correctly, but not with --dry-run, as the file is not created then.

I'll drop the second commit, fine with me.

On 20 June 2018 12:35:37 GMT+02:00, Steven Armstrong <notifications@github.com> wrote:
>Thanks for the patch.
>But to me it looks like you are using it wrongly.
>
>If the file does not exist we should fail. Question here is if we can
>fail in a more user friendly way then just letting awk die hard.
>
>We can't just create the file if it is not there. We have no clue how
>user/group/permissions should be.
>
>The proper way to use this is by using the __file type to ensure the
>file exists.
>
>e.g.
>```
>__file /tmp/my-file \
>   --state present
>require="__file/tmp/my-file" \
>   __line my-line \
>      --file /tmp/my-file \
>      --line 'hello world'
>```
>
>Like this the explorer works fine, because it is run after the __file
>type has done it's job.
>Also no need to create the file in gencode-remote.

-- 
mail@jonasw.de
https://jonasw.de/

**Comment by thriqon** [comment]
I've dropped the second commit. Could you take a look again, please?

**Pull request merged**
